//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENT_CATEGORY_LOOKUP
    {
        public long incident_category_id { get; set; }
        public string name { get; set; }
        public Nullable<long> incident_service_id { get; set; }
    
        public virtual INCIDENT_SERVICE_LOOKUP INCIDENT_SERVICE_LOOKUP { get; set; }
    }
}
