//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDemoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENT_BUSINESS_FUNCTION_LOOKUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INCIDENT_BUSINESS_FUNCTION_LOOKUP()
        {
            this.INCIDENT_SERVICE_LOOKUP = new HashSet<INCIDENT_SERVICE_LOOKUP>();
        }
    
        public long incident_business_id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCIDENT_SERVICE_LOOKUP> INCIDENT_SERVICE_LOOKUP { get; set; }
    }
}
